# site settings
title: Open Thrift
subtitle: 
email: luke.h.terry-1@ou.edu
description: Open Thrift is an easy to use mobile web application which will help college students efficiently and safely buy and sell goods.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
form_id:  # formspree endpoint
author:
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
phone: 414-837-8183

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: 
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
